---
name: test_app
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  carousel_pro: ^1.0.0
  cloud_firestore: 1.0.7
  curved_navigation_bar: 1.0.1
  firebase_admob: ^0.11.2
  firebase_analytics: 8.3.4
  firebase_auth: 3.3.0
  firebase_core: 1.10.2
  firebase_database: 8.2.0
  firebase_storage: 10.2.0
  flutter_spinkit: 4.1.2+1
  flutter_typeahead: 3.2.3
  fluttertoast: 8.0.8
  google_sign_in: 5.2.1
  http: 0.13.4
  image_picker: 0.8.4+4
  provider: 6.0.1
  quiver: 3.0.0
  shared_preferences: 2.0.9
  transparent_image: 2.0.0
  url_launcher: 6.0.17
  uuid: 3.0.5
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  sign_button: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - images/
  - images/ProPic.jpeg
